domain: http://summit.hotosm.org
baseurl: ''
permalink: pretty
exclude: [src, CNAME]
markdown: rdiscount

collections:
  speaker-list:
    output: true
  schedule-list:
    output: true
  events:
    ouput: true
